version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-with-api-gateway-sample"
s3_bucket = "{your-source-bucket}"
s3_prefix = "lambda-with-api-gateway-sample"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
